# np.sort
- return a sorted copy of array

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,100,15)
a

array([13, 17, 72, 83, 48, 96,  2, 16,  4, 86, 29, 40, 18, 98, 87])

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[16, 46, 33, 39],
       [81, 88, 91, 54],
       [92, 39, 75, 90],
       [15, 31, 54, 80],
       [66, 57, 77, 64],
       [44, 50, 91, 43]])

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

formula - numpy.sort(a, axis=-1, kind=None, order=None)[source]


In [7]:
np.sort(a)

array([ 2,  4, 13, 16, 17, 18, 29, 40, 48, 72, 83, 86, 87, 96, 98])

### # row vise sorting in 3d array

In [8]:
np.sort(b) 

array([[16, 33, 39, 46],
       [54, 81, 88, 91],
       [39, 75, 90, 92],
       [15, 31, 54, 80],
       [57, 64, 66, 77],
       [43, 44, 50, 91]])

### # column vise sorting - (axis = 0)

In [9]:
np.sort(b, axis = 0) 

array([[15, 31, 33, 39],
       [16, 39, 54, 43],
       [44, 46, 75, 54],
       [66, 50, 77, 64],
       [81, 57, 91, 80],
       [92, 88, 91, 90]])

####  reverse sorting

In [11]:
np.sort(a)[::-1]

array([98, 96, 87, 86, 83, 72, 48, 40, 29, 18, 17, 16, 13,  4,  2])

# np.append
- The numpy.appened() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [13]:
np.append(a,200)

array([ 13,  17,  72,  83,  48,  96,   2,  16,   4,  86,  29,  40,  18,
        98,  87, 200])

In [15]:
np.append(b, np.ones((b.shape[0],1)), axis = 1)

array([[16., 46., 33., 39.,  1.],
       [81., 88., 91., 54.,  1.],
       [92., 39., 75., 90.,  1.],
       [15., 31., 54., 80.,  1.],
       [66., 57., 77., 64.,  1.],
       [44., 50., 91., 43.,  1.]])

# np.concatenate
- it concat a sequence of arrays alon an existing axis. it generally use with tabular data (2d array)

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

#### numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

In [16]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [18]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,d), axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
- we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html

#### numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None, *, equal_nan=True)[source]


In [21]:
a = np.array([1,1,12,2,3,4,12,3,5,3,4,1])

In [22]:
np.unique(a)

array([ 1,  2,  3,  4,  5, 12])

# np.expand_dims

- we can get the expanded dimensional of array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

### numpy.expand_dims(a, axis)

In [23]:
a

array([ 1,  1, 12,  2,  3,  4, 12,  3,  5,  3,  4,  1])

In [25]:
a.shape

(12,)

In [24]:
np.expand_dims(a,axis = 0)

array([[ 1,  1, 12,  2,  3,  4, 12,  3,  5,  3,  4,  1]])

In [26]:
np.expand_dims(a,axis = 0).shape

(1, 12)

# converting row vector into column vector

In [27]:
np.expand_dims(a,axis = 1)

array([[ 1],
       [ 1],
       [12],
       [ 2],
       [ 3],
       [ 4],
       [12],
       [ 3],
       [ 5],
       [ 3],
       [ 4],
       [ 1]])

# np.where
- It return the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

### numpy.where(condition, [x, y, ]/)

In [28]:
a

array([ 1,  1, 12,  2,  3,  4, 12,  3,  5,  3,  4,  1])

In [29]:
# tell me the index position of whose value is greater than 4

In [30]:
np.where(a>4)

(array([2, 6, 8]),)

In [31]:
# replace value greater than 4 and replace with 0

In [32]:
np.where(a>4 , 0,a) # code (np.where(condition, true,false))

array([1, 1, 0, 2, 3, 4, 0, 3, 0, 3, 4, 1])

In [33]:
# replace even with 0.

In [34]:
np.where(a%2 == 0, 0,a)

array([1, 1, 0, 0, 3, 0, 0, 3, 5, 3, 0, 1])

# np.argmax
- return indices of the max elemnet of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

### numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)

In [36]:
a

array([ 1,  1, 12,  2,  3,  4, 12,  3,  5,  3,  4,  1])

In [38]:
np.argmax(a) # it will give maximum value index position

2

In [40]:
b

array([[16, 46, 33, 39],
       [81, 88, 91, 54],
       [92, 39, 75, 90],
       [15, 31, 54, 80],
       [66, 57, 77, 64],
       [44, 50, 91, 43]])

In [41]:
np.argmax(b, axis = 0) # axis 0 is column

array([2, 1, 1, 2])

# np.argmin
- give minimum value index position

In [42]:
np.argmin(a)

0

In [44]:
np.argmin(b, axis = 0)

array([3, 3, 0, 0])

# np.cumsum
- used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

#### numpy.cumsum(a, axis=None, dtype=None, out=None)[source]


In [46]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
np.cumsum(a)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276])

In [48]:
b

array([[16, 46, 33, 39],
       [81, 88, 91, 54],
       [92, 39, 75, 90],
       [15, 31, 54, 80],
       [66, 57, 77, 64],
       [44, 50, 91, 43]])

In [49]:
np.cumsum(b, axis = 0) in numpy array "0" on axis means column 

array([[ 16,  46,  33,  39],
       [ 97, 134, 124,  93],
       [189, 173, 199, 183],
       [204, 204, 253, 263],
       [270, 261, 330, 327],
       [314, 311, 421, 370]])

In [54]:
np.cumprod(b, axis = 0)

array([[         16,          46,          33,          39],
       [       1296,        4048,        3003,        2106],
       [     119232,      157872,      225225,      189540],
       [    1788480,     4894032,    12162150,    15163200],
       [  118039680,   278959824,   936485550,   970444800],
       [ 5193745920, 13947991200, 85220185050, 41729126400]])

# np.percentile
- It used to compute the nth percentile of the given data(array elements) along the specified axix.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

### numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, method='linear', keepdims=False, *, interpolation=None)


In [55]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
np.percentile(a,100)

23.0

In [59]:
np.percentile(a,50)

11.5

In [60]:
np.percentile(a,75)

17.25

In [62]:
np.median(a)

11.5

# np.histogram
- Numpy has a built in numpy.histogram() function which represents the frequency of data in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

### numpy.histogram(a, bins=10, range=None, density=None, weights=None)

In [87]:
np.histogram(a,bins = [0, 10, 20,30,40,50,60,70,80,90,100])

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [85]:
a = np.arange(0,100)

In [86]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [89]:
np.histogram(a, bins = [0,50,100])

(array([50, 50]), array([  0,  50, 100]))

# np.corrcoef
- Return person Product - moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

### numpy.corrcoef(x, y=None, rowvar=True, bias=<no value>, ddof=<no value>, *, dtype=None)

In [90]:
salary = np.array([200000,100000,50000,100000,150000,190000,350000,535000])

In [91]:
experience = np.array([2,1,1,1,2,2,3,4])

In [92]:
np.corrcoef(salary,experience)

array([[1.        , 0.97738699],
       [0.97738699, 1.        ]])

# np.isin
- with the help of numpy.isin() method, we can see that one array having values are checked in a different array having
different elements with different size.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

#### numpy.isin(element, test_elements, assume_unique=False, invert=False, *, kind=None)

In [93]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False])

In [96]:
a[np.isin(a,items)]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# np.flip

- reverse the order of array elements along the specified axis, preserving the shape of array.


https://numpy.org/doc/stable/reference/generated/numpy.flip.html

### numpy.flip(m, axis=None)[source]
- Reverse the order of elements in an array along the given axis.

- The shape of the array is preserved, but the elements are reordered.

In [97]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [98]:
np.flip(a)

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [99]:
b

array([[16, 46, 33, 39],
       [81, 88, 91, 54],
       [92, 39, 75, 90],
       [15, 31, 54, 80],
       [66, 57, 77, 64],
       [44, 50, 91, 43]])

In [100]:
np.flip(b)

array([[43, 91, 50, 44],
       [64, 77, 57, 66],
       [80, 54, 31, 15],
       [90, 75, 39, 92],
       [54, 91, 88, 81],
       [39, 33, 46, 16]])

In [101]:
np.flip(b, axis = 0)

array([[44, 50, 91, 43],
       [66, 57, 77, 64],
       [15, 31, 54, 80],
       [92, 39, 75, 90],
       [81, 88, 91, 54],
       [16, 46, 33, 39]])

In [102]:
np.flip(b,axis = 1)

array([[39, 33, 46, 16],
       [54, 91, 88, 81],
       [90, 75, 39, 92],
       [80, 54, 31, 15],
       [64, 77, 57, 66],
       [43, 91, 50, 44]])

# np.put (this function do permanent changes)

- replaces specific elements of an array with given values of p_array, array indexed work on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

### numpy.put(a, ind, v, mode='raise')
Replaces specified elements of an array with given values.

In [104]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [105]:
np.put(a,[0,1],[110,500])

In [106]:
a

array([110, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

# np.delete

- it returns a new array with the deletion of sub arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

### numpy.delete(arr, obj, axis=None)
Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

In [107]:
a

array([110, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [113]:
np.delete(a,0)

array([500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99])

In [114]:
np.delete(a,[0,2,4])

array([500,   3,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99])

# SET FUNCTIONS

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [115]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [116]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [118]:
np.intersect1d(m,n)

array([3, 4, 5])

In [119]:
np.setdiff1d(m,n)

array([1, 2])

In [120]:
np.setdiff1d(n,m)

array([6, 7])

In [121]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [122]:
np.setxor1d(n,m)

array([1, 2, 6, 7])

In [124]:
np.in1d(m,1)

array([ True, False, False, False, False])

# np.clip
- numpy.clip()function is used to clip(limit)the values in an array.
- it used some time in ML and mostly in DEEP LEARNING.

In [125]:
a

array([110, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [126]:
np.clip(a,a_min = 25, a_max = 75)

array([75, 75, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75,
       75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75])

In [127]:
np.unique(a)

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 110, 500])

# Numpy Meshgrid

- NumPy's meshgrid function is used to create a grid of points in two or three dimensions. It takes as input two or three 1D arrays representing the coordinates in each dimension, and returns the coordinates of all the points in the grid as two or three 2D arrays.

- Here is an example of how to use meshgrid in two dimensions:

In [130]:
import numpy as np

# Define the x and y coordinates
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])

# Create the grid
X, Y = np.meshgrid(x, y)

print(X)
# Output: [[-1  0  1]
#          [-1  0  1]
#          [-1  0  1]]

print(Y)
# Output: [[-2 -2 -2]
#          [ 0  0  0]
#          [ 2  2  2]]


[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[-2 -2 -2]
 [ 0  0  0]
 [ 2  2  2]]


- In this example, X is a 2D array where the rows are the values of y, and Y is a 2D array where the columns are the values of x.

- You can also use meshgrid in three dimensions by passing it three 1D arrays:

In [131]:
import numpy as np

# Define the x, y, and z coordinates
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
z = np.array([-3, 0, 3])

# Create the grid
X, Y, Z = np.meshgrid(x, y, z)



In [132]:
X

array([[[-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1]],

       [[-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1]],

       [[-1, -1, -1],
        [ 0,  0,  0],
        [ 1,  1,  1]]])

In [133]:
Y

array([[[-2, -2, -2],
        [-2, -2, -2],
        [-2, -2, -2]],

       [[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 2,  2,  2],
        [ 2,  2,  2],
        [ 2,  2,  2]]])

In [134]:
Z

array([[[-3,  0,  3],
        [-3,  0,  3],
        [-3,  0,  3]],

       [[-3,  0,  3],
        [-3,  0,  3],
        [-3,  0,  3]],

       [[-3,  0,  3],
        [-3,  0,  3],
        [-3,  0,  3]]])

- The resulting arrays X, Y, and Z are 3D arrays where the rows and columns are the values of y and z, and the third dimension is the values of x.

# Structured Numpy Array

- A structured NumPy array is an array that has a datatype with named fields. It is similar to a structured data type in C, and allows you to define an array that has a fixed number of elements, each with a fixed set of fields.

- Here is an example of how to create a structured array in NumPy:

In [135]:
import numpy as np

# Define the fields of the structured array
dtype = [('name', 'U10'), ('height', 'f4'), ('weight', 'f4')]

# Create the structured array
data = np.array([('Alice', 1.5, 50.), ('Bob', 1.6, 60.)], dtype=dtype)

print(data)
# Output:
# [('Alice', 1.5, 50.) ('Bob', 1.6, 60.)]


[('Alice', 1.5, 50.) ('Bob', 1.6, 60.)]


- In this example, we have created an array with two elements, each with three fields: 'name', 'height', and 'weight'. The 'U10' and 'f4' datatypes specify that the 'name' field is a Unicode string with a maximum length of 10 characters, and the 'height' and 'weight' fields are single-precision floating-point numbers.

- You can access the fields of a structured array using the dot notation:



In [136]:
# Access the first element of the 'name' field
print(data['name'][0])  # Output: 'Alice'

# Access the second element of the 'height' field
print(data['height'][1])  # Output: 1.6


Alice
1.6
